backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - label: "Project Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"

  - name: "gallery"
    label: "Gallery"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image Title", name: "title", widget: "string" }
      - label: "Gallery Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"
